<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.avaje</groupId>
    <artifactId>java11-oss</artifactId>
    <version>5.1</version>
  </parent>

  <groupId>io.ebean</groupId>
  <artifactId>ebean-datasource-parent</artifactId>
  <name>ebean-datasource-parent</name>
  <version>10.4-FOC2-SNAPSHOT</version>
  <packaging>pom</packaging>

  <scm>
    <developerConnection>scm:git:git@github.com:FOCONIS/ebean-datasource.git</developerConnection>
    <tag>HEAD</tag>
  </scm>

  <modules>
    <module>ebean-datasource</module>
    <module>ebean-datasource-api</module>
  </modules>

  <profiles>
    <profile>
      <id>foconis</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <distributionManagement>
        <repository>
          <id>foconis-release</id>
          <name>FOCONIS Release Repository</name>
          <url>https://mvnrepo.foconis.de/repository/release/</url>
        </repository>
        <snapshotRepository>
          <id>foconis-snapshot</id>
          <name>FOCONIS Snapshot Repository</name>
          <url>https://mvnrepo.foconis.de/repository/snapshot/</url>
        </snapshotRepository>
      </distributionManagement>
    </profile>
    <profile>
      <id>github</id>
      <distributionManagement>
        <repository>
          <id>github-release</id>
          <name>FOCONIS Github Release Repository</name>
          <url>https://maven.pkg.github.com/foconis/ebean-datasource</url>
        </repository>
      </distributionManagement>
    </profile>
    <profile>
      <id>central</id>
    </profile>
    <profile>
      <id>default</id>
      <activation>
        <activeByDefault />
      </activation>
      <modules>
        <module>blackbox-tests</module>
      </modules>
    </profile>
  </profiles>
</project>
